import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state of the counter
interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

// Create the slice
const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    // Increment the counter value by 1
    increment: (state) => {
      state.value += 1;
    },
    // Decrement the counter value by 1
    decrement: (state) => {
      state.value -= 1;
    },
    // Reset the counter value to a specified value (defaults to 0)
    reset: (state, action: PayloadAction<number>) => {
      state.value = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement, reset } = counterSlice.actions;

// Export the reducer to be used in the store
export default counterSlice.reducer;
